#------------------------------------------------------------- -*- makefile -*-
# makefile.vc --
#
#	Microsoft Visual C++ makefile for building the tserialport Tcl
#	extension with nmake. Based on the TIP 477 nmake build system
#	(rules-ext.vc / rules.vc / targets.vc), see
#	https://core.tcl-lang.org/tips/doc/trunk/tip/477.md
#
# Usage (from a Visual Studio developer command prompt, in this directory):
#
#	nmake -f makefile.vc TCLDIR=c:\path\to\tcl
#	nmake -f makefile.vc TCLDIR=c:\path\to\tcl LIBSERIALPORTDIR=c:\src\libserialport
#	nmake -f makefile.vc TCLDIR=c:\path\to\tcl install INSTALLDIR=c:\path\to\install
#	nmake -f makefile.vc TCLDIR=c:\path\to\tcl test
#
# Note: libserialport itself does not provide an nmake build system.
# libserialport.h and a prebuilt import library libserialport.lib are
# expected in $(LIBSERIALPORTDIR); the default is the embedded copy in
# $(ROOT)\libserialport.
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#------------------------------------------------------------------------------

PROJECT = tserialport
RCFILE = tserialport.rc

# libserialport: location of header and import library, override on the
# nmake command line when built elsewhere. ($(ROOT) is resolved by
# rules.vc to the project root.)
!ifndef LIBSERIALPORTDIR
LIBSERIALPORTDIR = $(ROOT)\libserialport
!endif

# $(ROOT) is also on the include path for the generated manifest.h.
PRJ_INCLUDES = -I"$(LIBSERIALPORTDIR)" -I"$(ROOT)"
PRJ_LIBS = "$(LIBSERIALPORTDIR)\libserialport.lib" setupapi.lib

# rules-ext.vc pulls in rules.vc which determines the package version
# from AC_INIT in $(ROOT)\configure.ac.
!include "rules-ext.vc"

PRJ_OBJS = $(TMP_DIR)\tserialport.obj

# tserialport.c includes the generated manifest.h; targets.vc adds
# PRJ_HEADERS as a dependency of PRJ_OBJS.
PRJ_HEADERS = $(ROOT)\manifest.h

# manifest.h is generated from the fossil manifest files in $(ROOT).
# mkversion.tcl -C changes into that directory before reading manifest,
# manifest.uuid and configure.ac.
$(ROOT)\manifest.h: $(ROOT)\manifest $(ROOT)\manifest.uuid $(TOOLSDIR)\mkversion.tcl
	$(TCLSH) "$(TOOLSDIR)\mkversion.tcl" -C "$(ROOT)" -defines >$@

!include "targets.vc"

pkgindex: default-pkgindex
